#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
(
    cd "${SCRIPT_DIR}/ansible"
    ansible-playbook -i inventories/production/hosts.yml playbooks/workstation.yml --ask-become-pass
)