---
- name: Configure workstation
  hosts: workstations
  become: false

  roles:
    - role: common
      tags: [common]
    - role: systemd
      tags: [systemd]
    - role: podman
      tags: [podman]
    - role: shell_config
      tags: [shell]
    - role: vscode
      tags: [vscode]
    - role: git_config
      tags: [git]
